# Generated by Django 5.1 on 2024-08-14 18:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('biography', models.TextField(blank=True, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='actors/')),
            ],
        ),
        migrations.CreateModel(
            name='Cinemas_Details',
            fields=[
                ('cid', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('role', models.CharField(default='cinema_manager', max_length=30)),
                ('phone', models.CharField(max_length=20)),
                ('city', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=200)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Flims_Details',
            fields=[
                ('mid', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('trailer', models.CharField(default='null', max_length=300)),
                ('release_date', models.CharField(default='null', max_length=20)),
                ('description', models.TextField()),
                ('poster', models.ImageField(default='', upload_to='movies')),
                ('genre', models.CharField(default='Action | Comedy | Romance', max_length=50)),
                ('duration', models.CharField(default='2hr 45min', max_length=10)),
                ('rating', models.DecimalField(decimal_places=1, max_digits=3)),
                ('upcoming', models.BooleanField(default=False)),
                ('nowshowing', models.BooleanField(default=False)),
                ('actors', models.ManyToManyField(blank=True, related_name='movies', to='MT_main.actor')),
            ],
        ),
        migrations.CreateModel(
            name='ShowDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True)),
                ('showdates', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='MT_main.cinemas_details')),
            ],
        ),
        migrations.CreateModel(
            name='ShowTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.CharField(max_length=100, null=True)),
                ('showtimes', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='MT_main.cinemas_details')),
            ],
        ),
        migrations.CreateModel(
            name='Shows_Details',
            fields=[
                ('sid', models.AutoField(primary_key=True, serialize=False)),
                ('price', models.IntegerField()),
                ('available_seats', models.IntegerField(default=100)),
                ('available_date', models.ManyToManyField(to='MT_main.showdate')),
                ('cinema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cinema_show', to='MT_main.cinemas_details')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movie_show', to='MT_main.flims_details')),
                ('time', models.ManyToManyField(to='MT_main.showtime')),
            ],
        ),
        migrations.CreateModel(
            name='Booking_shows',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_seat', models.CharField(max_length=300, null=True)),
                ('total_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('cinema_name', models.CharField(max_length=100, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('show_date', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='MT_main.showdate')),
                ('showtime', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='MT_main.showtime')),
            ],
        ),
    ]
