# Generated by Django 5.1 on 2024-08-19 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MT_main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='director',
            name='did',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
