# Generated by Django 5.1 on 2024-08-19 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MT_main', '0002_alter_director_did'),
    ]

    operations = [
        migrations.AddField(
            model_name='screening',
            name='total_seats',
            field=models.IntegerField(default=100),
        ),
    ]
