# Generated by Django 5.1 on 2024-08-16 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MT_main', '0004_alter_flims_details_trailer'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking_shows',
            name='cinema_location',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='booking_shows',
            name='cinema_name',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
