# Generated by Django 5.1 on 2024-08-21 19:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MT_main', '0006_alter_bookings_show_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookings',
            name='shows',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='MT_main.screening'),
        ),
    ]
