# Generated by Django 5.1 on 2024-08-16 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MT_main', '0006_booking_shows_total_seat_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking_shows',
            name='total_amt',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='booking_shows',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
