# Generated by Django 5.1 on 2024-08-16 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MT_main', '0007_booking_shows_total_amt_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking_shows',
            name='total_amt',
        ),
    ]
