# Generated by Django 5.1 on 2024-08-21 21:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MT_main', '0008_rename_shows_bookings_shows_show'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookings',
            name='shows_show',
        ),
    ]
