# Generated by Django 5.1 on 2024-08-22 06:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MT_main', '0009_remove_bookings_shows_show'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookings',
            name='screen',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='MT_main.screening'),
        ),
    ]
