# Generated by Django 5.1 on 2024-08-17 12:21

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MT_main', '0010_rename_flims_details_moviedetails_screening_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Booking_shows',
            new_name='Bookings',
        ),
        migrations.RenameModel(
            old_name='Cinemas_Details',
            new_name='Cinemas',
        ),
        migrations.RenameModel(
            old_name='MovieDetails',
            new_name='Movies',
        ),
    ]
