# Generated by Django 5.1 on 2024-08-22 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MT_main', '0010_bookings_screen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movies',
            name='trailer',
            field=models.URLField(blank=True, default='null', max_length=300, null=True),
        ),
    ]
