# Generated by Django 5.1 on 2024-08-17 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MT_main', '0011_rename_booking_shows_bookings_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cinemas',
            name='role',
            field=models.CharField(default='Cinema Admin', max_length=30),
        ),
    ]
