# Generated by Django 5.1 on 2024-08-23 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MT_main', '0011_alter_movies_trailer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movies',
            name='trailer',
            field=models.URLField(blank=True, default='', max_length=300, null=True),
        ),
    ]
