# Generated by Django 5.1 on 2024-08-23 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MT_main', '0012_alter_movies_trailer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movies',
            name='rating',
            field=models.DecimalField(decimal_places=1, default='4', max_digits=3),
        ),
    ]
