# Generated by Django 5.1 on 2024-08-23 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MT_main', '0013_alter_movies_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movies',
            name='release_date',
            field=models.CharField(default='', max_length=20, null=True),
        ),
    ]
