# Generated by Django 5.1 on 2024-08-23 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MT_main', '0014_alter_movies_release_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='movies',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, unique=True),
        ),
    ]
