# Generated by Django 5.1 on 2024-08-23 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MT_main', '0015_movies_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movies',
            name='slug',
        ),
    ]
