# Generated by Django 5.1 on 2024-08-24 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MT_main', '0017_remove_movies_nowshowing_remove_movies_upcoming_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actor',
            name='biography',
        ),
    ]
