# Generated by Django 5.1 on 2024-08-25 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MT_main', '0018_remove_actor_biography'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movies',
            name='rating',
            field=models.CharField(blank=True, default='4', max_length=5, null=True),
        ),
    ]
